markdownExploder: false
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: false
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: false
customTechnicalDocuments: null
devLoadAlwaysFiles: null
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
